# --
# ak | Docker Registry for Development v1.0
#
# Author(s):
#   - Alejandro M. BERNARDIS <ambernardis at asumikamikaze.com>
#   - Gabriel H. CETRARO <ghcetraro at asumikamikaze.com>
# Created: 2020-03-08
# ~

version: '3.4'

x-restart: &restart
  restart: unless-stopped

services:
  master:
    <<: *restart
    image: registry:2
    ports:
      - ${PORT}:5000
    environment:
      REGISTRY_LOG_LEVEL: warn
      REGISTRY_HTTP_HOST: http://${HOST}:${PORT}
      REGISTRY_REDIS_ADDR: ${MASTER_CACHE_LOCAL}:6379
      REGISTRY_REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ${BASEPATH}/auth:/auth:ro
      - ${BASEPATH}/data:/var/lib/registry:rw
      - ${BASEPATH}/config.yml:/etc/docker/registry/config.yml:rw
    networks:
      registry:
        aliases:
          - ${MASTER_LOCAL}
    depends_on:
      - master_cache

  master_cache:
    <<: *restart
    image: redis:5-alpine
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          memory: 256M
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ${BASEPATH}/cache:/data:rw
    networks:
      registry:
        aliases:
          - ${MASTER_CACHE_LOCAL}
    command: redis-server --loglevel warning

  master_web:
    <<: *restart
    image: klausmeyer/docker-registry-browser:latest
    ports:
      - ${PORT_UI}:8080
    environment:
      DOCKER_REGISTRY_URL: http://${MASTER_LOCAL}:${PORT}
      PUBLIC_REGISTRY_URL: ${HOST}:${PORT}
      NO_SSL_VERIFICATION: 'true'
      ENABLE_DELETE_IMAGES: 'true'
    networks:
      registry:
        aliases:
          - ${MASTER_WEB_LOCAL}
    depends_on:
      - master

networks:
  registry:
    external:
      name: registry
